### ISSUE TITLE
Newly added ILI9341 display does not work 

### ISSUE THREAD

**Issue by markbirss** [satoshinm/oledterm#3]
root@raspberrypi:/home/pi/oledterm# python oledterm.py --display ili9341 --interface spi --rotate 2 --width 320 --height 240
Traceback (most recent call last):
  File "oledterm.py", line 112, in <module>
    device = get_device()
  File "oledterm.py", line 38, in get_device
    device = cmdline.create_device(args)
  File "/usr/local/lib/python2.7/dist-packages/luma/core/cmdline.py", line 197, in create_device
    device = Device(serial_interface=serial, **params)
  File "/usr/local/lib/python2.7/dist-packages/luma/lcd/device.py", line 465, in __init__
    self.clear()
  File "/usr/local/lib/python2.7/dist-packages/luma/core/mixin.py", line 46, in clear
    self.display(Image.new(self.mode, self.size))
  File "/usr/local/lib/python2.7/dist-packages/luma/lcd/device.py", line 489, in display
    self.data(self.framebuffer.image.crop(self.framebuffer.bounding_box).tobytes())
  File "/usr/local/lib/python2.7/dist-packages/luma/core/device.py", line 46, in data
    self._serial_interface.data(data)
  File "/usr/local/lib/python2.7/dist-packages/luma/core/interface/serial.py", line 215, in data
    self._write_bytes(data[i:i + tx_sz])
  File "/usr/local/lib/python2.7/dist-packages/luma/core/interface/serial.py", line 291, in _write_bytes
    self._spi.writebytes(data)
TypeError: Non-Int/Long value in arguments: b6768380.

**Comment by markbirss** [comment]
python3 does not show same error but crashes with other error, cannot access permissions to /dev/console
